spring:
  datasource:
    url: jdbc:mysql://localhost:3306/highway-hub?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: root
    password: 1995
    hikari:
      maximum-pool-size:  20
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update


server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/