#server:
#  port: 8080
#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: user-service
#            uri: lb://user-service
#            predicates:
#              - path=/user-service/**
#          - id: vehicle-service
#            uri: lb://vehicle-service
#            predicates:
#              - path=/vehicle-service/**
#          - id: ticket-service
#            uri: lb://ticket-service
#            predicates:
#              - path=/ticket-service/**
#          - id: payment-service
#            uri: lb://payment-service
#            predicates:
#              - path=/payment-service/**

server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



