server:
  port: 8081
spring:
  application:
    name: config-server
  profiles:
    active: native
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

